#! /usr/bin/env bash

help() {
  # This prints a help page which provides a list of options.
  HELP_MESSAGE='This is a place holder for the real help message.'
  printf "%s" "${HELP_MESSAGE}"
}

main() {
  while getopts "h" OPTION; do
    case "${OPTION}" in
      h)
        help
        exit 1;;
    esac
  done
}

main "${@}"
